//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CammandPatternTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Contact
    {
        public int id { get; set; }
        [Required]
        public string username { get; set; }
        [Required]
        public string Subject { get; set; }
        [Required]
        public string Details { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Login_table Login_table { get; set; }
    }
}
